apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gratibot-db
spec:
  selector:
    matchLabels:
      app: gratibot-db
  serviceName: "gratibot"
  replicas: 1
  template:
    metadata:
      labels:
        app: gratibot-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: "{{ .Values.mongo.image }}"
        strategy:
          type: recreate
        volumeMounts:
        - mountPath: /mongo-data
          name: mongo-data
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storageClassName | default "gp2" }}
      resources:
        requests:
          storage: "2Gi"

